// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3eb9a899-b584-4e6b-8f1a-ddf6fc081f00",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hSSxcuw2d",
    "aws_user_pools_web_client_id": "17elaejue4v42v8gjrfc9v4eum",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "cmpe281proj1db-prod",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "cmpe-281-project18a4b1af95152455cab4fe6abb7a93f51-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "s3api",
            "endpoint": "https://t99q4m7xx5.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
